import "../styles/index.css";
import cn from "classnames";
import { Inter, DM_Sans, Poppins } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-dm-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Dazal Design Studio",
  description: "Generated by Dazal Design Studio",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={cn(
        inter.variable,
        poppins.variable,
        dmSans.variable
      )}>
        {children}
      </body>
    </html>
  );
}